# Generated by Django 6.0.8 on 2026-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appearance", "0004_powerautomatedelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiBobEmployee",
            fields=[
                ("hibob_id", models.TextField(db_column="hibob_root_id", primary_key=True, serialize=False)),
                ("employee_id", models.TextField(db_column="hr_work_employeeidincompany")),
                ("full_name", models.TextField(blank=True, db_column="raw_root_fullname", null=True)),
                ("display_name", models.TextField(blank=True, db_column="raw_root_displayname", null=True)),
                ("role", models.TextField(blank=True, db_column="hr_work_title", null=True)),
                ("raw_role", models.TextField(blank=True, db_column="raw_work_title", null=True)),
                ("lifecycle_status", models.TextField(blank=True, db_column="hr_internal_lifecyclestatus", null=True)),
            ],
            options={
                "verbose_name": "HiBob employee (read only)",
                "verbose_name_plural": "HiBob employees (read only)",
                "db_table": '"hibob_etl"."employees"',
                "managed": False,
            },
        ),
        migrations.RenameIndex(
            model_name="tattoorecord",
            new_name="appearance__employe_e3014d_idx",
            old_name="appearance__employe_290a15_idx",
        ),
    ]
